# Default values for domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domainUID: null
operatorNamespace: weblogic-operator
domainsNamespace: default

podDomainLogsDir: /domain-logs
podDomainHomeDir: /domain-home

weblogicDomainCredentialsSecretName: null
#weblogicImage: store/oracle/weblogic:12.2.1.3
weblogicImage: null
weblogicImagePullPolicy: IfNotPresent

domainLogsPersistentVolumeEnabled: false
domainLogsPersistentVolumeDir: null

internalOperatorCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0RENDQXB5Z0F3SUJBZ0lFYmhEMGpEQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RjMNClpXSnNiMmRwWXkxdmNHVnlZWFJ2Y2pBZUZ3MHhPREEyTVRReE56STNNamxhRncweU9EQTJNVEV4TnpJM01qbGENCk1Cd3hHakFZQmdOVkJBTVRFWGRsWW14dloybGpMVzl3WlhKaGRHOXlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYNCkFBT0NBUThBTUlJQkNnS0NBUUVBcVVKWGYvMTFzZlNEQ1puQ1dTUVhqWk9Wc2ljT0dXN3hFUzd0dDk2ODdvTGINClpJMGpBVFU2YUdTK3BvVVFRNUZ3amh4Q2xTajBUbjdVTEg4T0E5V1gvUU9IWmcwVFlrUEVtcGRGaEJFdGVrMDgNClgrSEZKaTg0OHBnZ2EyT1djZCtSTTZxaEVwR1RHRUY1OGk0Y0FMTUFHRkhJNHU0dzF1eCtLUmszbUVDczd0NVANCjVrY2NnenNRTnVZZUFBbm5QMTZ4L3VKN0VTbjg3NllIY1VTOCtmenNxZzRtUEtYQ3QzN242cTVVOGF4c3FEMEUNCjdKeDQrOXRDYkdGY1JiY3NPbS9rd3FmWU0wbG1ranprTUxNa0VWNjlYVUpIUWc2bE9WcWs5Y0xQY3NNcEQ0SGMNCjNtUHhPL1UzUFpMb1VNMGhNNzdRRWZNZUpFRUVyVEJMQXJzalRKblNaUUlEQVFBQm80SDlNSUg2TUFzR0ExVWQNCkR3UUVBd0lEK0RDQnl3WURWUjBSQklIRE1JSEFnaDVwYm5SbGNtNWhiQzEzWldKc2IyZHBZeTF2Y0dWeVlYUnYNCmNpMXpkbU9DTEdsdWRHVnlibUZzTFhkbFlteHZaMmxqTFc5d1pYSmhkRzl5TFhOMll5NTBiVzl5WldGMUxXOXcNCkxXNXpnakJwYm5SbGNtNWhiQzEzWldKc2IyZHBZeTF2Y0dWeVlYUnZjaTF6ZG1NdWRHMXZjbVZoZFMxdmNDMXUNCmN5NXpkbU9DUG1sdWRHVnlibUZzTFhkbFlteHZaMmxqTFc5d1pYSmhkRzl5TFhOMll5NTBiVzl5WldGMUxXOXcNCkxXNXpMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNQjBHQTFVZERnUVdCQlFQMHJVRktLcjJ3SHk2NEZQRHhSNHINCmc3R0JSakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBb3pxMUw5Uk93Vks3WjczTzRlR00xTUhvTG43bXpORUINCll6U2FmcG1HUk5KL3NBY0tUT2c0dm1IK3RUdGZrMW1xeUhOUFRjSklRTjAzNitmSE1Nb2ZXd3UycUpLNWZ5LzANCmpPendTUyt1VklOV3FQbXhyMFFPaWthUFp1SmE2NWd5WDB5a054S1RjcGtFa1FoWDhaNDVxSDZkZUt1aFNtU1MNCjNpeFpZZk02WFBNUG8rK1czQUNTek43NTh0M1FXSHl5M09GaURKMEJqNmo0UG4zOFlwL09Kc04yWG1GbTZENzgNCjNFSncyMDdZdWEwcHNwRUFCVllBZHp6bHYvNGt1NVZET2M5N3QwaGpRNkIzOUpCR0VwVUdXVmxvZ0xYS2RhR0cNCm1lMndHRXRPVFpjcEdMbTlTUDI1U2kwTnVRTmMvSHlrMzZMSEtHLzlvR1dMQkhyc0pwWGNPUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

customPodTemplates: {}
customAdminServerPodTemplates: {}
customManagedServerPodTemplates: {}

#temporarily manually create the default templates.
#need to rework this so it's like the weblogic pod stuff
adminServerServiceTemplates:
  default: {}
adminServerT3ServiceTemplates:
  default: {}
managedServerServiceTemplates:
  default: {}

extraEnv: {}
extraVolumeMounts: {}
extraVolumes: {}
extraResources: {}
