{{- $values := .Values }}
{{- range $key, $element := $values.sitCfgGenerators }}
{{-   $podTemplateName := $element.podTemplate }}
{{-   range $k, $e := $values.podTemplates }}
{{-     if eq $k $podTemplateName }}
{{-       $podTemplate := $e }}
{{-       $weblogicImage           := $e.weblogicImage           | default $values.weblogicImage }}
{{-       $weblogicImagePullPolicy := $e.weblogicImagePullPolicy | default $values.weblogicImagePullPolicy }}
{{-       $extraVolumes            := $e.extraVolumes            | default $values.extraVolumes }}
{{-       $extraVolumeMounts       := $e.extraVolumeMounts       | default $values.extraVolumeMounts }}
---
kind: ConfigMap
metadata:
  labels:
    weblogic.createdByOperator: "true"
    weblogic.operatorName: {{ $values.operatorNamespace }}
    weblogic.domainUID: {{ $values.domainUID }}
    weblogic.resourceVersion: domain-v1
  name: {{ $values.domainUID }}-{{ $key }}-generator-cm
  namespace: {{ $values.domainsNamespace }}
data:
  sitcfg-generator-pod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        weblogic.createdByOperator: "true"
        weblogic.domainUID: {{ $values.domainUID }}
        weblogic.resourceVersion: domain-v1
      name: {{ $values.domainUID }}-{{ $key }}-generator
      namespace: {{ $values.domainsNamespace }}
    spec:
      containers:
      - command:
        - /weblogic-operator/scripts/generateSitCfg.sh
        env:
        - name: DOMAIN_UID
          value: {{ $values.domainUID }}
        - name: DOMAIN_HOME
          value: {{ $values.podDomainHomeDir }}
        - name: DOMAIN_LOGS
          value: {{ $values.podDomainLogsDir }}
        - name: SITCFG_NAME
          value: {{ $key }}
        image: {{ $weblogicImage }}
        imagePullPolicy: {{ $weblogicImagePullPolicy }}
        livenessProbe:
          exec:
            command:
            - /weblogic-operator/scripts/sitCfgGeneratorLivenessProbe.sh
          failureThreshold: 25
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: weblogic-server
        readinessProbe:
          exec:
            command:
            - /weblogic-operator/scripts/sitCfgGeneratorReadinessProbe.sh
          failureThreshold: 1
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: weblogic-credentials-volume
          mountPath: /weblogic-operator/secrets
          readOnly: true
        - name: weblogic-domain-cm-volume
          mountPath: /weblogic-operator/scripts
          readOnly: true
{{- if $extraVolumeMounts }}
{{ toYaml $extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: weblogic-credentials-volume
        secret:
          defaultMode: 420
          secretName:  {{ $values.weblogicDomainCredentialsSecretName }}
      - name: weblogic-domain-cm-volume
        configMap:
          defaultMode: 365
          name: weblogic-domain-cm 
{{- if $extraVolumes }}
{{ toYaml $extraVolumes | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
